# Generated by Django 2.2.5 on 2020-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du raccourci')),
                ('pseudo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.IntegerField(default=0, verbose_name="Nombre d'accès au raccourci")),
            ],
            options={
                'verbose_name': 'Mini URL',
                'verbose_name_plural': 'Minis URL',
            },
        ),
    ]
