# Generated by Django 2.2.5 on 2020-06-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniurl',
            old_name='nombre',
            new_name='nombre_acces',
        ),
    ]
