# Generated by Django 2.2.5 on 2020-06-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0002_auto_20200612_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='nombre_acces',
            field=models.IntegerField(default=0, verbose_name="Nombre d'accès à l'URL"),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL à réduire'),
        ),
    ]
